# Generated by Django 5.2.3 on 2025-06-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialcambios',
            options={'verbose_name': 'Historial cambio', 'verbose_name_plural': 'Historial cambios'},
        ),
        migrations.RenameField(
            model_name='planterapeutico',
            old_name='metas_especificas',
            new_name='metas_específicas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Foto'),
        ),
    ]
