# Generated by Django 5.2.3 on 2025-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_alter_historialcambios_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_paciente',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En Pausa', 'En Pausa'), ('Dado de Alta', 'Dado de Alta'), ('No Acude', 'No Acude'), ('Nuevo', 'Nuevo')], default='Activo', max_length=20, verbose_name='Estado del Paciente'),
        ),
    ]
