# Generated by Django 5.2.3 on 2025-07-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_alter_paciente_estado_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto_offset_x',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Posición X de la Foto'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_offset_y',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Posición Y de la Foto'),
        ),
    ]
